#!/bin/sh
if [ $# != 1 ];then
	echo "usage: wds-clear VAP_ID(0~7)";
	return
fi

VAP_ID=$1
if [ $VAP_ID -lt 0 -o $VAP_ID -gt 7 ];then
	echo "Invalid VAP_ID ${VAP_ID}";
	return
fi

wlanconfig wds${VAP_ID} nawds list | while read l;
do
    echo $l | grep '[a-fA-F0-9]\{2\}:[a-fA-F0-9]\{2\}:[a-fA-F0-9]\{2\}:[a-fA-F0-9]\{2\}:[a-fA-F0-9]\{2\}:[a-fA-F0-9]\{2\}' > /dev/null;
    if [ $? -eq 0 ];then
		MAC=`echo $l|awk '{print $2}'`;
		echo wlanconfig wds${VAP_ID} nawds del-repeater ${MAC};
		wlanconfig wds${VAP_ID} nawds del-repeater ${MAC};
    fi
done;
